### ISSUE TITLE
Scenarios fail due to Open5GS configuration file format change

### ISSUE THREAD

**Issue by pau-alef** [giros-dit/containerized-cellular-testbeds#1]
Hi,

While testing the `5g-sa_open5gs_ueransim` scenario I realized that the `open5gs` daemons fail to start and there is no error caught.

It seems there was an `open5gs` configuration format change recently that breaks your configurations. You can find some information pointers here, which faced the same issue:

https://osmocom.org/issues/6267

I was able to launch the scenario successfully modifying the Docker file to check out `v2.6.6`

**Comment by david-martinez-garcia** [comment]
Hello @pau-alef,

Thanks for reporting this. I’ll have a look at this as soon as the circumstances allow me and will update the repository with new configuration files.

**Comment by pau-alef** [comment]
> Hello @pau-alef,
> 
> Thanks for reporting this. I’ll have a look at this as soon as the circumstances allow me and will update the repository with new configuration files.

Below you have working configs:

`amf.yaml`

```
logger:
  file: /var/log/open5gs/amf.log
  # level: info   # fatal|error|warn|info(default)|debug|trace

global:
  max:
    ue: 1024  # The number of UE can be increased depending on memory size.

amf:
  sbi:
    server:
      - address: 10.254.1.1
        port: 7777
    client:
      scp:
        - uri: http://10.254.1.7:7777

  ngap:
    server:
      - address: 10.100.1.1
        # Add port if different from default

  metrics:
    server:
      - address: 127.0.0.5
        port: 9090

  guami:
    - plmn_id:
        mcc: 001
        mnc: 01
      amf_id:
        region: 1
        set: 1

  tai:
    - plmn_id:
        mcc: 001
        mnc: 01
      tac: 1

  plmn_support:
    - plmn_id:
        mcc: 001
        mnc: 01
      s_nssai:
        - sst: 1

  security:
    integrity_order : [ NIA2, NIA1, NIA0 ]
    ciphering_order : [ NEA0, NEA1, NEA2 ]

  network_name:
    full: GIROS-DIT
  amf_name: giros-dit-amf0

  time:
    t3512:
      value: 540    # 9 minutes * 60 = 540 seconds
```


`ausf.yaml`

```
logger:
  file: /var/log/open5gs/ausf.log
  # level: info   # fatal|error|warn|info(default)|debug|trace

global:
  max:
    ue: 1024  # The number of UE can be increased depending on memory size.

ausf:
  sbi:
    server:
      - address: 10.254.1.2
        port: 7777
    client:
      scp:
        - uri: http://10.254.1.7:7777
```


`bsf.yaml`

```
logger:
  file: /var/log/open5gs/bsf.log
  # level: info   # fatal|error|warn|info(default)|debug|trace

global:
  max:
    ue: 1024  # The number of UE can be increased depending on memory size.
    # peer: 64

bsf:
  sbi:
    server:
      - address: 10.254.1.3
        port: 7777
    client:
      scp:
        - uri: http://10.254.1.7:7777
```


`nrf.yaml`

```
logger:
  file: /var/log/open5gs/nrf.log
  # level: info   # fatal|error|warn|info(default)|debug|trace

global:
  max:
    ue: 1024  # The number of UE can be increased depending on memory size.

nrf:
  sbi:
    server:
      - address: 10.254.1.4
        port: 7777
        no_tls: true
        cacert: /open5gs/install/etc/open5gs/tls/ca.crt
        key: /open5gs/install/etc/open5gs/tls/nrf.key
        cert: /open5gs/install/etc/open5gs/tls/nrf.crt
      - address: ::1
        port: 7777
        no_tls: true
        cacert: /open5gs/install/etc/open5gs/tls/ca.crt
        key: /open5gs/install/etc/open5gs/tls/nrf.key
        cert: /open5gs/install/etc/open5gs/tls/nrf.crt
```


`nssf.yaml`

```
logger:
  file: /var/log/open5gs/nssf.log
  # level: info   # fatal|error|warn|info(default)|debug|trace

global:
  max:
    ue: 1024  # The number of UE can be increased depending on memory size.
    # peer: 64

nssf:
  sbi:
    server:
      - address: 10.254.1.5
        port: 7777
    client:
      scp:
        - uri: http://10.254.1.7:7777
      nsi:
        - uri: http://127.0.0.10:7777
          s_nssai:
            sst: 1
```


`pcf.yaml`

```
db_uri: mongodb://10.254.1.100/open5gs
logger:
  file: /var/log/open5gs/pcf.log
  # level: info   # fatal|error|warn|info(default)|debug|trace

global:
  max:
    ue: 1024  # The number of UE can be increased depending on memory size.
    # peer: 64

pcf:
  sbi:
    server:
      - address: 10.254.1.6
        port: 7777
    client:
      scp:
        - uri: http://10.254.1.7:7777
  metrics:
    server:
      - address: 127.0.0.13
        port: 9090
```


`scp.yaml`

```
logger:
  file: /var/log/open5gs/scp.log
  # level: info   # fatal|error|warn|info(default)|debug|trace

global:
  max:
    ue: 1024  # The number of UE can be increased depending on memory size.
    # peer: 64 (uncomment and set this if needed)

scp:
  sbi:
    server:
      - address: 10.254.1.7
        port: 7777
        no_tls: true
        cacert: /open5gs/install/etc/open5gs/tls/ca.crt
        key: /open5gs/install/etc/open5gs/tls/scp.key
        cert: /open5gs/install/etc/open5gs/tls/scp.crt
    client:
      nrf:
        - uri: http://10.254.1.4:7777
```


`smf.yaml`

```
logger:
  file: /var/log/open5gs/smf.log
  # level: info   # fatal|error|warn|info(default)|debug|trace

global:
  max:
    ue: 1024  # The number of UE can be increased depending on memory size.
    # peer: 64

smf:
  sbi:
    server:
      - address: 10.254.1.8
        port: 7777
    client:
      scp:
        - uri: http://10.254.1.7:7777
  pfcp:
    server:
      - address: 10.100.1.2
    client:
      upf:
        - address: 10.100.1.3
  gtpc:
    server:
      - address: 10.100.1.2
  gtpu:
    server:
      - address: 10.100.1.2
  metrics:
    server:
      - address: 127.0.0.4
  session:
    - subnet: 172.45.1.1/24
      dnn: internet
  dns:
    - 8.8.8.8
    - 8.8.4.4
  mtu: 1400
  # p-cscf:
  #   - 127.0.0.1
  #   - ::1
  ctf:
    enabled: auto
  freeDiameter: /open5gs/install/etc/freeDiameter/smf.conf

# Additional SMF-specific configurations can be added here

parameter:
  # Additional parameters can be added here
```


`udm.yaml`

```
logger:
  file: /var/log/open5gs/udm.log
  # level: info   # fatal|error|warn|info(default)|debug|trace

global:
  max:
    ue: 1024  # The number of UE can be increased depending on memory size.
#    peer: 64

udm:
  hnet:
    - id: 1
      scheme: 1
      key: /open5gs/install/etc/open5gs/hnet/curve25519-1.key
    - id: 2
      scheme: 2
      key: /open5gs/install/etc/open5gs/hnet/secp256r1-2.key
    - id: 3
      scheme: 1
      key: /open5gs/install/etc/open5gs/hnet/curve25519-3.key
    - id: 4
      scheme: 2
      key: /open5gs/install/etc/open5gs/hnet/secp256r1-4.key
    - id: 5
      scheme: 1
      key: /open5gs/install/etc/open5gs/hnet/curve25519-5.key
    - id: 6
      scheme: 2
      key: /open5gs/install/etc/open5gs/hnet/secp256r1-6.key
  sbi:
    server:
      - address: 10.254.1.9
        port: 7777
    client:
      scp:
        - uri: http://10.254.1.7:7777
```


`udr.yaml`

```
db_uri: mongodb://10.254.1.100/open5gs

logger:
  file: /var/log/open5gs/udr.log
  # level: info   # fatal|error|warn|info(default)|debug|trace

global:
  max:
    ue: 1024  # The number of UE can be increased depending on memory size.
#    peer: 64

udr:
  sbi:
    server:
      - address: 10.254.1.10
        port: 7777
    client:
      scp:
        - uri: http://10.254.1.4:7777
```


`upf.yaml`

```
logger:
  file: /var/log/open5gs/upf.log
  # level: info   # fatal|error|warn|info(default)|debug|trace

global:
  max:
    ue: 1024  # The number of UE can be increased depending on memory size.

upf:
  pfcp:
    server:
      - address: 10.100.1.3
  gtpu:
    server:
      - address: 10.100.1.3
  session:
    - subnet: 172.45.1.1/24
      dev: ogstun
      dnn: internet
  metrics:
    server:
      - address: 127.0.0.7
        port: 9090
```
